DROP TABLE IF EXISTS Record;
DROP TABLE IF EXISTS Data;
DROP TABLE IF EXISTS Sample;
DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS Animal;

CREATE TABLE Person (
PersonID INT NOT NULL PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
City VARCHAR(64) NOT NULL,
State VARCHAR(2) NOt NULL,
Country VARCHAR(3) NOT NULL
);

CREATE TABLE Animal (
AnimalID VARCHAR(100) NOT NULL PRIMARY KEY,
Name VARCHAR(128) NOT NULL,
Breed VARCHAR(64) NOT NULL,
Species VARCHAR(16) NOT NULL,
RegNum VARCHAR(128)
);

CREATE TABLE Sample (
Valid VARCHAR(8) NOT NULL,
CanNum VARCHAR(32) NOT NULL,
AnimalID VARCHAR(32) NOT NULL,
CollDate VARCHAR(128),
NumUnits INT NOT NULL,
PersonID INT NOT NULL,
Notes VARCHAR(1000),
FOREIGN KEY (PersonID) REFERENCES kabsu.person (PersonID),
FOREIGN KEY (AnimalID) REFERENCES kabsu.animal (AnimalID)
);

CREATE TABLE Record (
AnimalID VARCHAR(32) NOT NULL,
ToFrom VARCHAR(100) NOT NULL,
Date VARCHAR(32) NOT NULL,
NumReceived INT NOT NULL,
NumShipped INT NOT NULL,
Balance INT NOT NULL,
FOREIGN KEY (AnimalID) REFERENCES kabsu.animal (AnimalID)
);

CREATE TABLE Data (
AnimalID VARCHAR(32) NOT NULL,
Date VARCHAR(32) NOT NULL,
Notes VARCHAR(256) NOT NULL,
Vigor INT NOT NULL,
Mot INT NOT NULL,
Morph INT NOT NULL,
Code INT NOT NULL,
Units INT NOT NULL,
FOREIGN KEY (AnimalID) REFERENCES kabsu.animal (AnimalID)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/People.csv'
INTO TABLE person
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES terminated by '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Animal.csv'
INTO TABLE animal
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES terminated by '\n'
IGNORE 1 ROWS;

DROP TABLE IF EXISTS tempsample;

CREATE TABLE tempsample (
Valid VARCHAR(8) NOT NULL,
CanNum VARCHAR(32) NOT NULL,
Code VARCHAR(100) NOT NULL,
CollDate VARCHAR(128),
NumUnits INT NOT NULL,
AnimalName VARCHAR(128) NOT NULL,
Breed VARCHAR(64) NOT NULL,
RegNum VARCHAR(128),
Notes VARCHAR(1000),
PersonName VARCHAR(100) NOT NULL,
Town VARCHAR(64) NOT NULL,
State VARCHAR(2) NOT NULL
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/sample.csv'
INTO TABLE tempsample
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

INSERT INTO sample (Valid, CanNum, AnimalID, CollDate, NumUnits, PersonID, Notes)
SELECT Valid, CanNum, TS.Code, CollDate, NumUnits, P.PersonID, Notes
FROM tempsample TS
	INNER JOIN person P ON P.Name = TS.PersonName AND P.City = TS.Town
	INNER JOIN animal A ON A.AnimalID = TS.Code;

DROP TABLE tempsample;